[package]
name = "pimalaya-stream"
description = "Stream, TLS and SASL utils for Pimalaya"
version = "0.0.1"
authors = ["soywod <pimalaya.org@posteo.net>"]
rust-version = "1.87"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "network-programming"]
keywords = ["pimalaya", "stream", "tls", "sasl", "tcp"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/pimalaya-stream/latest/pimalaya_stream"
repository = "https://github.com/pimalaya/stream"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rustls-ring"]
std = ["dep:uds_windows"]
native-tls = ["std", "dep:native-tls"]
rustls-aws = ["std", "dep:rustls", "dep:rustls-platform-verifier", "rustls/aws-lc-rs"]
rustls-ring = ["std", "dep:rustls", "dep:rustls-platform-verifier", "rustls/ring"]
vendored = ["native-tls?/vendored"]

[dependencies]
anyhow = { version = "1", default-features = false, features = ["std"] }
log = { version = "0.4", default-features = false }
native-tls = { version = "0.2", default-features = false, optional = true }
rustls = { version = "0.23", default-features = false, features = ["logging", "std", "tls12"], optional = true }
rustls-platform-verifier = { version = "0.7", default-features = false, optional = true }
secrecy = { version = "0.10", default-features = false }
url = { version = "2.2", default-features = false }

[target.'cfg(windows)'.dependencies]
uds_windows = { version = "1", optional = true }
